### PR TITLE
Issue 22: Add toggle to not refresh breaking news

### LINKED ISSUE #22: Add toggle to not refresh breaking news
As a developer, I want to add a toggle to disable refreshing of breaking news on the Simulato test site to better test breaking news components separate from other components.

Acceptance Criteria:
- Toggle for refreshing breaking news
- Functions to not refresh breaking news despite refreshing other news

References QE-2089.

### PR DESCRIPTION
**Pull request by zmknox**
Closes #22.

Changes in this pull request:
- Added button to disable refreshing of breaking news header
- Some minor tweaks to make the site more responsive

References QE-2089.

### CODE REVIEW

**Review by tomrdale — CHANGES_REQUESTED** [review]
It looks like your "Breaking News Refresh On" state lets me NOT refresh and "Breaking News Refresh Off" Lets me refresh

**Comment by zmknox** [comment]
@tomrdale It's a button, it says what will happen when you press it: it will turn off when you press "Breaking News Refresh Off".

**Comment by tomrdale** [comment]
> @tomrdale It's a button, it says what will happen when you press it: it will turn off when you press "Breaking News Refresh Off".

The issue says a toggle, so I was expecting toggle behavior/syntax. Do we want to change it to just a simple toggle? Or leave as a button.

**Comment by zmknox** [comment]
The button does function as a toggle, switching what it does on press. Ideally it would look like a switch, though Bootstrap doesn't really have a component for that. Should I change it to a checkbox? That might make more contextual sense

**Comment by tomrdale** [comment]
This works, it meets the goals of being able to acceptance test simulato if its a button or checkbox so no worries.

**Review by tomrdale — APPROVED** [review]

**Pull request merged**
